version: '3'

services:
  frontend:
    build:
      args:
        REACT_APP_API_URL: "wss://${DOMAIN}/api/websocket"
      context: frontend
    restart: unless-stopped
  backend:
    build:
      context: backend
    restart: unless-stopped
    environment:
      SERVER_CHECK_ORIGIN: "${DOMAIN}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      DEBUG_ENABLED: "${DEBUG_ENABLED:-false}"
      GAME_ROUND_TIMEOUT: ${GAME_ROUND_TIMEOUT:-2m}
      SERVER_ADDRESS: "0.0.0.0:8081"
  ngrok:
    image: ngrok/ngrok:3.3.5-alpine
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--domain=${DOMAIN}"
      - "nginx:80"
  nginx:
    image: nginx:1.25.2-alpine3.18
    ports:
      - 127.0.0.1:8081:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
